spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=GENRATED_SECRET_KEY
jwt.expiration=3600000

spring.redis.host=localhost
spring.redis.port=6379
