spring.application.name=demo
server.port=8094

spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=kavita@13

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=mZ7zK3y9Q1x8Vb2Lp0Rt6Wn5sF4HcJk2Pq8UvXyZaBc=
jwt.expiration=12000

spring.redis.host=localhost
spring.redis.port=6379






