spring.application.name=demo
server.port=8094

spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=kavita@13

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=bXl2ZXJ5c2VjdXJlc2VjcmV0a2V5bXl2ZXJ5c2VjcmV0a2V5MTIz
jwt.expiration=120000

spring.redis.host=localhost
spring.redis.port=6379






