spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=your_secret
jwt.expiration=120000

spring.redis.host=localhost
spring.redis.port=6379