spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=kavita@13

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=Z5QBa/7y/BKg7qaGu5mNiLxYdtwkQd5COUyN8sHFu7g=

jwt.expiration=3600000

spring.data.redis.host=localhost
spring.data.redis.port=6379